name: Build artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

    - name: Purge artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: 0

    - name: Get New Release Tag
      id: new-release-tag
      run: |
        tag=$(cat src/main/resources/mod.json | grep "version*" | cut -d ":" -f 2,3 | tr -d \"," ")
        echo '::set-output name=tag::'$tag

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: MindurkaCompat
        path: ./build/libs/MindurkaCompat-${{ steps.new-release-tag.outputs.tag }}.jar

    - name: Create release
      id: create-release

      if: ${{ steps.check-release-tag.outputs.exists == 'false' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.new-release-tag.outputs.tag }}
        release_name: Release ${{ steps.new-release-tag.outputs.tag }}

    - name: Upload release assets
      id: upload-release-assets

      if: ${{ steps.check-release-tag.outputs.exists == 'false' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./build/libs/MindurkaCompat-${{ steps.new-release-tag.outputs.tag }}.jar
        asset_name: DarkdustryPlugin-${{ steps.new-release-tag.outputs.tag }}.jar
        asset_content_type: application/java-archive
